services:
  - type: web
    name: socialrank-bolivia-dashboard
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://socialrank-bolivia-api-news.onrender.com/noticias/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
